module.exports = {
   content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
   theme: {
      extend: {},
      fontFamily: {
         sans: ['Inter', 'sans-serif'],
      },
   },
   plugins: [require('daisyui')],
   daisyui: {
      styled: true,
      themes: [
         {
            mytheme: {
               "primary": "#606c38",
               "secondary": "#dda15e",
               "accent": "#bc6c25",
               "neutral": "#283618",
               "base-100": "#d8f3dc",
               "info": "#48cae4",
               "success": "#94d2bd",
               "warning": "#ee9b00",
               "error": "#ae2012",
            },
         },
         'light',
         'dark',
         'cupcake',
         'bumblebee',
         'emerald',
         'corporate',
         'synthwave',
         'retro',
         'cyberpunk',
         'valentine',
         'halloween',
         'garden',
         'forest',
         'aqua',
         'lofi',
         'pastel',
         'fantasy',
         'wireframe',
         'black',
         'luxury',
         'dracula',
         'cmyk',
         'autumn',
         'business',
         'acid',
         'lemonade',
         'night',
         'coffee',
         'winter',
      ],
      base: true,
      utils: true,
      logs: true,
      rtl: false,
   },
};
